name: chat_sample
description: Chat Sample

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: 0.4.0
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  fluttertoast: ^3.1.3
  cached_network_image: 2.0.0-rc.1
  photo_view: ^0.5.0
  lottie: ^0.6.0
  flutter_svg: 0.18.0
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/
    - assets/images/
    - assets/icons/